### PR TITLE
[release-0.18] Don't wipe internal model when relaxation=true

### PR DESCRIPTION
**Pull request by joehuchette**
ref #1208

### CODE REVIEW

**Comment by mlubin** [comment]
I did a quick check and didn't find a test that runs `solve(m, relaxation=true)` and then `solve(m, relaxation=false)` and checks that the integer constraints are respected.

**Comment by odow** [comment]
There is a test here 

https://github.com/JuliaOpt/JuMP.jl/blob/aa22198d8448a3cad69b42772bb09f8a61b9ec70/test/model.jl#L857-L862

**Comment by mlubin** [comment]
Ah, good find. That's tested with:
https://github.com/JuliaOpt/JuMP.jl/blob/aa22198d8448a3cad69b42772bb09f8a61b9ec70/test/solvers.jl#L64-L67
so there's no coverage on travis. Could we check that this works with Cbc and GLPK (without asking for duals)?

**Comment by odow** [comment]
Just tested with Cbc, Gurobi, and CPLEX. All seems to work.

**Comment by mlubin** [comment]
And GLPK?

**Pull request merged**
