### PR TITLE
tidy up expression graphs

### PR DESCRIPTION
**Pull request by mlubin**
For https://github.com/JuliaOpt/AmplNLWriter.jl/issues/39
CC @JackDunnNZ

### CODE REVIEW

**Comment by mlubin** [comment]
@JackDunnNZ, my example [here](https://github.com/JuliaOpt/AmplNLWriter.jl/issues/39#issuecomment-237339527) still gives an error:
```
ERROR: MethodError: `process_expression!` has no method matching process_expression!(::Int64, ::Dict{Int64,Float64}, ::Array{Symbol,1})
```

and your example [here](https://github.com/JuliaOpt/AmplNLWriter.jl/issues/39#issuecomment-226366919) now seems to crash ipopt.

**Comment by JackDunnNZ** [comment]
Ipopt seems to die if there's no objective, changing the example to:

```julia
using JuMP
using AmplNLWriter

m = Model(solver=IpoptNLSolver())
@variable(m, x)
@NLconstraint(m, x <= sum{0, j = []})
@objective(m, Max, x)
solve(m)
```

fixes things there. Just looking at the other one now

**Comment by JackDunnNZ** [comment]
The error with the Convex example comes because the constraint `x^2 <= 5` gets transformed into a set of constraints that includes `0 <= 1.0`, giving:

```
ERROR: MethodError: `process_expression!` has no method matching process_expression!(::Int64, ::Dict{Int64,Float64}, ::Array{Symbol,1})
Closest candidates are:
  process_expression!(::Expr, ::Dict{Int64,Float64}, ::Array{Symbol,1})
```

because `0` isn't an `Expr`. If I add the definition to process this special case:

```julia
function process_expression!(nonlin_expr::Real, lin_expr, varlinearities)
    0, nonlin_expr, :Lin
end
```
the .nl file becomes malformed because there's a constraint with no variables involved, and no solver will open it. 

@mlubin Why is it giving this empty constraint? And where should we head it off and delete it?

**Comment by mlubin** [comment]
``0 <= 1.0`` is a valid constraint

**Comment by JackDunnNZ** [comment]
Yes, but not in an .nl file. I'm happy to deal with it, just wanted to make
sure you didn't want to handle it further up

**Comment by mlubin** [comment]
I think AmplNLWriter should be cleaning this one up. JuMP isn't in the business of preprocessing out constraints.

**Comment by JackDunnNZ** [comment]
Will do

**Comment by JackDunnNZ** [comment]
Great, thanks for this too!

**Pull request merged**
