### PR TITLE
Expose getnodecount #442

### PR DESCRIPTION
**Pull request by sbebo**
Wrapper for  `MathProgBase.getnodecount `.

### CODE REVIEW

**Comment by joehuchette** [comment]
Great, thanks for this. Looks good to me.

**Comment by joehuchette** [comment]
A sneaky way to handle a lot of the remaining ``MathProgBase.get*(::JuMP.Model)`` methods at once would be to use an ``@eval`` loop, since the body of of the functions will end up looking much the same (like here for ``getnodecount`` and ``getsolvetime``).

**Comment by mlubin** [comment]
@joehuchette, I was just thinking that as well. We can do that after merging though.

**Comment by joehuchette** [comment]
Thanks @sbebo!

**Pull request merged**
