### PR TITLE
document querying derivatives from a JuMP model

### LINKED ISSUE #352: document getting an AbstractNLPEvaluator from a JuMP model
We should have a documented method to extract an AbstractNLPEvaluator from a JuMP model. This will make it easy to explicitly evaluate derivatives or extract expression graphs from a model for experimental purposes.

CC @tkelman

### PR DESCRIPTION
**Pull request by mlubin**
Closes #352 
CC @tkelman @dpo

### CODE REVIEW

**Comment by dpo** [comment]
That's great! The notebook you pointed me to earlier also has good examples worth mentioning.

**Comment by mlubin** [comment]
CC @rgiordan

**Comment by mlubin** [comment]
@dpo, I've expanded the docs and implemented ``buildInternalModel``, so now it should be easy to extract the standard-form representation from a JuMP model.

**Comment by dpo** [comment]
Many thanks, Miles! I'll be able to give it a whirl tomorrow.

**Pull request merged**
