### PR TITLE
Document Bonmin, Couenne, CoinOptServices and AmplNLWriter

### LINKED ISSUE #497: Document CoinOptServices and AmplNLWriter

### PR DESCRIPTION
**Pull request by tkelman**
closes #497

Look good?

### CODE REVIEW

**Comment by mlubin** [comment]
Thanks @tkelman. The wide columns make the table a bit harder to read, maybe a linebreak after the "or"? No idea how to do this though.
As part of #497 I also wanted to document that you can use ``AmplNLWriter`` to connect to many solvers not listed.

**Comment by tkelman** [comment]
Ah yeah, definitely good to mention that AmplNLWriter can talk to any other non-listed solver that AMPL can. Will add that as a new bullet.

I thought there would be a line break after the or if you check the rst input, but the rendering is too clever I guess. Not sure if github rendering will match RTD.

**Comment by mlubin** [comment]
There's no line break when I build it locally with the RTD theme

**Comment by tkelman** [comment]
You and @JackDunnNZ may want to expand on that, tweak the wording, adjust the formatting, etc. The branch is in this repo.

**Comment by mlubin** [comment]
Yeah, we'll do that.

**Comment by JackDunnNZ** [comment]
LGTM, thanks! My only tweak would to link directly to the AMPL-compatible solvers page: http://ampl.com/products/solvers/all-solvers-for-ampl/

**Comment by tkelman** [comment]
Miles said the same thing on 64c3d32f725bf1acea3d6d13c272fcaa7de925ec which I force-pushed over (s/Julia/JuMP/), but I'll stop pushing to this now and let you guys have at it.

**Comment by mlubin** [comment]
I'm seeing a lot of test failures for ``OsilSolver``. @tkelman, are you aware of these?

**Comment by tkelman** [comment]
Which platform, which versions and branches of things? There's an issue in LightXML that needs to be tagged for 0.4, and some issues with WinRPM.

**Comment by mlubin** [comment]
Ref https://github.com/JuliaOpt/CoinOptServices.jl/issues/6 for the above comment

@tkelman, would you be offended if we more explicitly recommend the ``.nl`` versions of Bonmin and Couenne over the ``.osil`` versions for both stability and performance reasons?

**Comment by tkelman** [comment]
I thought I already did.

**Comment by mlubin** [comment]
Thanks! I tweaked the formatting to get the different solvers on multiple lines.

**Pull request merged**
