### PR TITLE
Precompile JuMP

### PR DESCRIPTION
**Pull request by joehuchette**
Seems to work (along with https://github.com/JuliaOpt/MathProgBase.jl/pull/80).

### CODE REVIEW

**Comment by mlubin** [comment]
What's the improvement in import time?

**Comment by joehuchette** [comment]
Not sure how to (easily) wipe the precompilation for v0.4 for comparison, but against v0.3 I get:
```
~❯ time j -e "using JuMP"
/Users/huchette/julia/julia -e "using JuMP"  0.83s user 0.10s system 109% cpu 0.842 total
~❯ time julia3 -e "using JuMP"
/Applications/Julia-0.3.8.app/Contents/Resources/julia/bin/julia -e   6.43s user 0.24s system 95% cpu 7.015 total
```

**Comment by IainNZ** [comment]
LGTM

**Comment by tkelman** [comment]
Awesome.

**Pull request merged**
