### PR TITLE
[RFC]: add solvehook/printhook functionality

### PR DESCRIPTION
**Pull request by joehuchette**
Ref #275, is this what you had in mind @mlubin?

### CODE REVIEW

**Comment by IainNZ** [comment]
I'd really like a printing hook too, so can we have either
```julia
setSolveHook(
setPrintHook(
```
or
```julia
setHook(:solve
setHook(:print
```
(I guess with value dispatching in Julia 0.4 they'd be almost identical!)

**Comment by joehuchette** [comment]
What would this be used for? Any calls to printing of JuMP models/variables/constraints, etc?

**Comment by IainNZ** [comment]
A JuMP extension (like JuMPeR) can't currently use `print` because print doesn't do anything with extensions. So I have `printRobust` and `solveRobust`. One option with printing would be to have `print(::Model)` try to call a print on each extensions object in the extension dict, OR we can do the hook thing for printing too. I'm going to use this solve hook thing to get rid of `solveRobust`, iff the solve hook can return e.g. a false that'll break out of JuMP's solve without it doing anything.

**Comment by joehuchette** [comment]
I think a hook for ``print(::Model)`` makes more sense than trying to deal with everything in the extension dict directly. I _think_ the solve hook functionality will work with JuMPeR if you just add ``ignore_solve_hook=true`` to each of the ``solve`` calls in ``solveRobust``.

**Comment by mlubin** [comment]
I don't mind two separate hooks for solve and print. We'll eventually make this nice but let's just experiment a bit first to see what works.

**Comment by joehuchette** [comment]
Added printing hook as well.

**Comment by IainNZ** [comment]
Yeah I think this is cool, and really smooths nicely over one of the more awkward things with extensions (not being able to dispatch on the model type).

**Comment by waTeim** [comment]
say, how general is "printing" do you have some ideas on visualizing?

**Comment by joehuchette** [comment]
Not really, but we're definitely interested in any suggestions!

**Comment by waTeim** [comment]
Well, something I've been playing around with recently.  Idea is Julia + atom-shell + d3.  If something could export something (JSON in a IOBuffer maybe), then it could be read and then yielded by a generator and then rendered fairly arbitrarily.

**Comment by mlubin** [comment]
LGTM. We're sort of emulating virtual methods but that's okay.

**Comment by IainNZ** [comment]
Will this be 0.7.4 or 0.8?

**Comment by joehuchette** [comment]
I'd prefer 0.7.4 so I can start using it. I didn't add docs or NEWS, but I'm thinking it would fit best in the extension docs PR #286

**Comment by joehuchette** [comment]
Also thinking that maybe I shouldn't have exported the new functions

**Pull request merged**
