### PR TITLE
Add  plural macros for expressions and NLexpressions with tests

### PR DESCRIPTION
**Pull request by odow**

### CODE REVIEW

**Comment by mlubin** [comment]
I like it. Could you clear up the merge conflicts?

**Comment by mlubin** [comment]
(See https://github.com/JuliaOpt/JuMP.jl/pull/761)

**Comment by joehuchette** [comment]
Very cool, thanks!

Minor style point: could you please change the macro calls to use parentheses? E.g. ``@variable(m, x)``, ``@expressions(m, begin ... end)``.

**Comment by odow** [comment]
@mlubin here you go

**Comment by mlubin** [comment]
Looks good here, would you mind squashing the commits?

**Comment by odow** [comment]
@mlubin

**Pull request merged**
