### PR TITLE
Pass on kwargs to solve hook

### PR DESCRIPTION
**Pull request by IainNZ**
This is pretty essential to make JuMPeR work as it is right now. Without this I'll need to have some option-setting lines before the solve, which doesn't feel good.
If this is OK, can it be v0.7.5?

### CODE REVIEW

**Comment by mlubin** [comment]
LGTM.

**Comment by joehuchette** [comment]
Yep, looks good. What do you need the new release for? (Not that I'm opposed, just wondering)

**Comment by IainNZ** [comment]
Trying to tag a JuMPeR v0.1  :D

**Comment by joehuchette** [comment]
:+1: 

BTW what's the deal with the release failure on PkgEvaluator?

**Comment by IainNZ** [comment]
Wooah... only on 0.3 too. I haven't pushed the run from this morning but I manually checked and it has happened again...

**Comment by IainNZ** [comment]
Figured it out - was because I had precompiled JuMP into Julia 0.3, and I don't build it every night. This was a baffling error!

**Comment by IainNZ** [comment]
AppVeyor failure seems to be due to download issues.

**Pull request merged**
