### PR TITLE
[release-0.18] small 1.0 compatibility fixes to writers.jl

### PR DESCRIPTION
**Pull request by ExpandingMan**
Closes https://github.com/JuliaOpt/JuMP.jl/issues/1474
Closes https://github.com/JuliaOpt/JuMP.jl/issues/1473
Closes https://github.com/JuliaOpt/JuMP.jl/pull/1475

### CODE REVIEW

**Comment by ExpandingMan** [comment]
Sorry, forgot the [release-0.18] label.

**Comment by ExpandingMan** [comment]
Woah... what the hell is going on, now all of the sudden we are getting segfaults as soon as tests start on 0.6?  How could this be happening in both these PR's? 😕

**Comment by ExpandingMan** [comment]
Well, I'm not even able to reproduce the segfault.  I'm pretty sure I'm using exactly the same set of packages that are being used by travis.  As an experiment, I tried removing the outer `@testset` macro from the `print.jl` file where the segfault occurs.

It seems we are faced with a rather scary heisenbug, I'm pretty stumped on what to do about this.

**Comment by ExpandingMan** [comment]
Ok: the good news is that the segfault is definitely occuring somewhere within the "Model" tests in `print.jl`.  Hopefully I'll be able to find it with just a little more effort.

In the meantime, there seems to be some error with `Clp`
```
/home/travis/julia/bin/julia: symbol lookup error: /home/travis/.julia/v0.6/Clp/src/../deps/usr/lib/libClp.so: undefined symbol: _ZN18CoinMessageHandlerlsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
================================[ ERROR: JuMP ]=================================
failed process: Process(`/home/travis/julia/bin/julia -Cgeneric -J/home/travis/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=user --color=no --compilecache=yes /home/travis/.julia/v0.6/JuMP/test/runtests.jl`, ProcessExited(127)) [127]
================================================================================
```

Any ideas?

**Comment by blegat** [comment]
@juan-pablo-vielma Any idea about the Clp undefined symbol ?

**Comment by juan-pablo-vielma** [comment]
None :-) Is it reproducible outside of travis?

**Comment by ExpandingMan** [comment]
Ok here's where we are:  The constraint on line 368 of `test/print.jl` of this PR is triggering a segfault.  I have no idea why, and I cannot reproduce on one of my machines (even with apparently identical setup).  For the time being, I have commented it and all associated tests (3) out, just to let travis finish so that we can resolve all other issues.

As far as the segfault itself goes, I'm not really sure what's the best course of action here.  As I cannot reproduce it, it will be incredibly difficult to actually create a proper work-around.  To be honest, if it were up to me I'd probably just remove that constraint and change the associated tests accordingly on 0.6 only, but, in the interest in full transparency, my motivation for this is that I do not care one bit about what happens on 0.6 (and there has never been a segfault on 0.7 or 1.0).  If anyone has any better suggestions I'd be happy to implement them.

**Comment by ExpandingMan** [comment]
Wow, another segfault.  I think we might be in pretty big trouble here.

**Comment by mlubin** [comment]
I re-ran travis at the head of `release-0.18` and the segfault still occurs (https://travis-ci.org/JuliaOpt/JuMP.jl/jobs/425341084#L7004). That would suggest that a new version of a dependency is triggering the segfault. This is indeed hard to debug if it can't be reproduced locally. Worst case you could probe by setting upper bounds on package dependencies in `REQUIRE`.

**Comment by ianfiske** [comment]
@ExpandingMan I made a PR for you with that small change https://github.com/ExpandingMan/JuMP.jl/pull/1 so we can give it a try.

**Comment by ianfiske** [comment]
Progress!  It didn't segfault, but instead failed a test

```
Testing basic operator overloads: Error During Test at /home/travis/build/JuliaOpt/JuMP.jl/test/operator.jl:79
  Got exception UndefVarError(:prinltn) outside of a @test
  UndefVarError: prinltn not defined
  Stacktrace:
   [1] macro expansion at /home/travis/build/JuliaOpt/JuMP.jl/src/macros.jl:285 [inlined] (repeats 2 times)
   [2] macro expansion at /home/travis/build/JuliaOpt/JuMP.jl/test/operator.jl:81 [inlined]
   [3] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Test/src/Test.jl:1079 [inlined]
   [4] macro expansion at /home/travis/build/JuliaOpt/JuMP.jl/test/operator.jl:80 [inlined]
   [5] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Test/src/Test.jl:1079 [inlined]
   [6] top-level scope at /home/travis/build/JuliaOpt/JuMP.jl/test/operator.jl:50
```

**Comment by ianfiske** [comment]
@ExpandingMan one more fix for that here:  https://github.com/ExpandingMan/JuMP.jl/pull/2

**Comment by ExpandingMan** [comment]
@ianfiske any ideas about what specifically in Clp.jl was causing that segfault?  At some point we'll need 0.5.0 to pass tests on Julia 1.0.

**Comment by ExpandingMan** [comment]
Well, capping ForwardDiff worked for now, though I wouldn't be at all surprised if the bug is still lurking in there.  We are still getting the error where it seems unable to find the `libClp` shared library.

**Comment by ExpandingMan** [comment]
With Clp capped at 0.5.0 the library error goes away, but we now get a `Cbc` error:
```
Problem modification part two with Cbc.CbcMathProgSolverInterface.CbcSolver(Any[(:logLevel, 0)]): Error During Test
  Test threw an exception of type UndefVarError
  Expression: solve(m) == :Optimal
  UndefVarError: getconstrmatrix not defined
  Stacktrace:
   [1] setwarmstart!(::Cbc.CbcMathProgSolverInterface.CbcMathProgModel, ::Array{Float64,1}) at /home/travis/.julia/v0.6/Cbc/src/CbcSolverInterface.jl:215
   [2] #build#121(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::JuMP.Model) at /home/travis/.julia/v0.6/JuMP/src/solvers.jl:409
```
(see the travis)

So here's that status:
1. There is a mysterious segfault which is likely coming from a dependency thanks to @mlubin 's check of the `release-0.18` head.  I've never been able to reproduce this segfault locally, and it's never been seen on Julia 0.7 or later.  Since the segfault happens early in the tests, it seems likely that, if it's coming from a dependency, it's coming from a JuMP dependency and not a test dependency.  I haven't seen the segfault since capping ForwardDiff at 0.9, though, if we can't find the segfault, that still doesn't do us any  good because we need ForwardDiff 0.9 or later for Julia 1.0.  It of course wouldn't surprise me if the segfault is there and does not involve ForwardDiff directly.
2. Cbc, Clp seem to be having various problems, in particular the error where it can't seem to find `libClp`.

As for me, I am not going to start digging into the dependencies in order to fix this.  My only interest in this was getting JuMP 0.18 working on Julia 1.0.  As far as I can tell we are pretty much there.  It's extremely unfortunate that we found ourselves in a situation where we had to continue support for 0.6 even when we are adding 0 features or fixes (for obvious reasons), we really should never have allowed that to happen as 0.6, being technically a pre-release, is rapidly becoming ancient history and this is very different from the situation we would be in were this the 2.0 boundary.

Of course, if you guys are able to fix all the issues with 0.6 here, I'd be happy to push this PR through to the end once you make patches to the dependencies.  Otherwise, if this remains in purgatory, at some point I'm simply going to tag a branch on my fork, use that, and look forward to the real work of helping to address the concerns I had with 0.19 that motivated my work on 0.18 in the first place.

Anyway, thanks all.  If you make changes to the dependencies and want me to trigger travis on this PR again, please let me know and I'll do so.

**Comment by mlubin** [comment]
Issues with the dependencies likely affect both 0.6 and 1.0 so we'll want to address them in any case. The discussion about dropping 0.6 support seems out of place since tests are still not passing on 0.7/1.0. If the segfault on 0.6 is the blocker and we're sure that this PR is otherwise correct, we can merge and continue.

I fixed the issue with Cbc here: https://github.com/JuliaOpt/Cbc.jl/pull/71. I also just tagged a version of SCS compatible with 1.0 (https://github.com/JuliaLang/METADATA.jl/pull/18244).

**Comment by ExpandingMan** [comment]
Sorry, I don't mean to get into an argument about the validity of 0.6 as it seems the ship has long since sailed (and I started working on this knowing full well that 0.6 was always going to be supported), but one of my points was that whatever is causing the segfault is ultimately a Julia issue (in the formal sense at the very least, since Julia is not supposed to segfault and it seems unlikely to me that this is coming from bad `Ptr` code as there is evidence it's not a C wrapper causing this) and there is a good chance that it has been fixed either deliberately or as a consequence of other changes by 1.0.  Besides that, if the segfault were occurring in 1.0 it would be our due diligence to file an issue in the Julia repo and help them fix it, while our recourse in the 0.6 case is somewhat less clear.  I have a whole list of other reasons, but rather than argue about it I'd prefer to just help everyone fix it and move on :slightly_smiling_face: .

Anyway, thanks for your help with Cbc and SCS.  I'll re-trigger this once a Cbc patch is merged.  Note that we still have the problem with `libClp`.

**Comment by mlubin** [comment]
> Note that we still have the problem with libClp.

If this is the only known issue with solvers, you can comment Clp out as a test dependency temporarily and proceed. GLPK also covers much of the same code.

**Comment by ExpandingMan** [comment]
Hey guys, sorry I was MIA for a while.  Glad thinks are progressing, thanks all.

**Pull request merged**
