### PR TITLE
Remove variable 'categories'

### PR DESCRIPTION
**Pull request by IainNZ**
This is a left over from very early naming choices I made, we use type everywhere pretty much, even in MPB. Here is me paying for past sins.

### CODE REVIEW

**Comment by mlubin** [comment]
``getType`` seems like it could be confused with a generic julia function (besides the camel case)

**Comment by mlubin** [comment]
That's why we have ``getCategory``

**Comment by joehuchette** [comment]
Yeah, is this just a renaming?

**Comment by IainNZ** [comment]
This is just a renaming. In MPB we use type, and almost everywhere inside JuMP we use `vartype`, `v_type`, `t`, except for here. It makes it awkward to talk about - I'd have preferred to use category throughout, but I guess it didn't stick so now we're in a strange spot.

**Comment by IainNZ** [comment]
So, what you guys thinking?

**Comment by joehuchette** [comment]
I dunno, seems like a lot of churn for a change I'm not really convinced is better than what's there now.

**Comment by mlubin** [comment]
Where are all the places that we're currently using type over category? A grep for vartype shows:
```
type GenericQuadExpr{CoefType,VarType}
```
I know MPB uses vartype, but that doesn't mean we have to.

**Comment by IainNZ** [comment]
At a glance:
- MPB
- `t` in `@defVar`, `writers.jl`
- `setCategory` itself refers to it as a `type` in its error message + arguments, and we refer to a list of `var_types`: https://github.com/JuliaOpt/JuMP.jl/blob/e0164566e953616c6c9e4bd0eacc3d5b03be6372/src/JuMP.jl#L419
- `vartypes_without_fixed` https://github.com/JuliaOpt/JuMP.jl/blob/e0164566e953616c6c9e4bd0eacc3d5b03be6372/src/solvers.jl#L471-L480

**Comment by IainNZ** [comment]
If you prefer category, we can go the other way as well. I don't think its good how it is now.

**Comment by IainNZ** [comment]
I kind of like category, I just figured that maybe you guys didn't.

**Comment by mlubin** [comment]
I actually prefer category.

**Pull request closed without merging**
