### PR TITLE
DNMY: remove BonminNLSolver and CouenneNLSolver

### PR DESCRIPTION
**Pull request by odow**
Wait for JuliaOpt/AmplNLWriter.jl#66 to be merged and a new version of AmplNLWriter tagged.

Ref https://github.com/JuliaOpt/JuMP.jl/pull/1130/files

### CODE REVIEW

**Comment by mlubin** [comment]
https://github.com/JuliaOpt/JuMP.jl/pull/1105 needs to be backported to this branch and the docs need to be regenerated on top of this.
@joaquimg

**Comment by joaquimg** [comment]
Will do.
Btw, why do we like .nl more than .osil for these solvers?

**Comment by mlubin** [comment]
.nl is a more reliable interface.

**Comment by mlubin** [comment]
@odow could you update this with the changes from #1105?

**Comment by odow** [comment]
Is there an easy way to rebuild the docs on windows?

**Comment by mlubin** [comment]
No clue, but I'll do it.

**Comment by joaquimg** [comment]
Sorry, I thougth this was to be merged first.

**Pull request merged**
