### PR TITLE
fix expression graph output for comparisons on 0.5

### PR DESCRIPTION
**Pull request by mlubin**
@JackDunnNZ, does this resolve the issue in https://github.com/JuliaOpt/AmplNLWriter.jl/issues/36?

### CODE REVIEW

**Comment by JackDunnNZ** [comment]
Yes it does thanks, I've also got changes for JuliaOpt/CoinOptServices.jl#16 that work after this too. I'll tidy them up and PR soon.

**Comment by mlubin** [comment]
Cool, I'll merge and tag this soon so your PRs have a shot at passing CI.

**Comment by JackDunnNZ** [comment]
That reminds me, should I bother locking the changes behind a specific 0.5 build, or just any 0.5 like you have here?

**Comment by mlubin** [comment]
Any 0.5 should be fine. We don't intend to support any 0.5 prerelease versions other than the latest

**Pull request merged**
