### PR TITLE
Returning infeasibility ray for SOCP duals

### PR DESCRIPTION
**Pull request by emreyamangil**
Adding support for infeasibility ray for SOCP duals. Will add tests tomorrow!

### CODE REVIEW

**Comment by mlubin** [comment]
Looking good, thanks!

**Comment by joehuchette** [comment]
Mind squashing this? Then we can merge

**Comment by emreyamangil** [comment]
Oh damn I am failing on this :( Isn't this supposed to work?

git rebase -i HEAD~5

and replace all pick from 2nd to 5th by squash, save, 

git commit && git push --set-upstream infray?

**Comment by emreyamangil** [comment]
It worked right??? :)

**Comment by joehuchette** [comment]
Haha, nope :)

The way I usually do it is:
```
git rebase -i master
# change all but one commit to f
# resolve the conflicts
git push origin +infray
```

**Comment by joehuchette** [comment]
Though that remote might not be right, you should put ``origin`` to whatever the name for the remote for your fork is

**Comment by emreyamangil** [comment]
Oh NOOOEEESS!! So when I do git rebase -i master, I should squash the 2nd to 6th commits right??

**Comment by emreyamangil** [comment]
I was hopeful that these would work :)

git reset --soft HEAD~5
git commit -m 'new commit message'

but it so didn't!

**Comment by joehuchette** [comment]
Yes, or ``f``, which just lumps all the changes into one commit. 

Before you do the last step (the ``+`` is a "force" update), check ``git log`` to verify that there's a single commit that does what you want.

**Comment by emreyamangil** [comment]
wooops! after git rebase -i master, I am getting an error, but git log shows single commit, if i git push origin +infray, then it complains i dont have the permission, so much confusion!!! sorry Joey! :(

**Comment by joehuchette** [comment]
Do ``git remote -v`` to see what the address for your fork is. It should be something like
```
joehuchette	git@github.com:joehuchette/Gadfly.jl.git (fetch)
joehuchette	git@github.com:joehuchette/Gadfly.jl.git (push)
origin	git://github.com/dcjones/Gadfly.jl.git (fetch)
origin	git@github.com:dcjones/Gadfly.jl.git (push)
```
The ``joehuchette`` is the remote name for my fork; you should have something analogous locally (like ``git@github.com:emreyamangil/JuMP.jl.git``, I'd guess)

**Comment by joehuchette** [comment]
Then you can do ``git push __your_name_here__ +infray``

**Comment by emreyamangil** [comment]
It didn't work :( I got a ton of reading to do!!!

after git rebase -i master, I replaced the 2nd-6th commits with squash, save and exit, it complains about some error:

error: could not apply fe0dc47... fill in infeasibility ray

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Could not apply fe0dc473376d267ae4364d8547e3804f2f22e561... fill in infeasibility ray

then git log shows single commit, then git remote -v shows

conicdualjump	https://github.com/emreyamangil/JuMP.jl.git (fetch)
conicdualjump	https://github.com/emreyamangil/JuMP.jl.git (push)
infray	https://github.com/emreyamangil/JuMP.jl.git (fetch)
infray	https://github.com/emreyamangil/JuMP.jl.git (push)
myjump	https://github.com/emreyamangil/JuMP.jl.git (fetch)
myjump	https://github.com/emreyamangil/JuMP.jl.git (push)
myjump2	https://github.com/emreyamangil/JuMP.jl.git (fetch)
myjump2	https://github.com/emreyamangil/JuMP.jl.git (push)
origin	https://github.com/JuliaOpt/JuMP.jl.git (fetch)
origin	git@github.com:JuliaOpt/JuMP.jl.git (push)

(I have no idea why other upstreams are still showing up, I just did a hard reset!!!) 

Then I do git push infray +infray, it says all up to date :( I am such a noob!!!!!!!!!!

**Comment by joehuchette** [comment]
Did you finish the rebase? You need to go through the files, there will be some chunks delimited with
```
>>>>
# some code on one branch
====
# same code, on another
<<<<
This is the chunks of code git can't figure out how to merge, so you need to do it by resolving it manually (i.e. replacing the entire chunk above with the correct code). Once you've done that, do ``git rebase --continue`` and repeat as necessary.

**Comment by emreyamangil** [comment]
It only has this, confusion!!!

pick 5987b5c add infeasibility ray support to SOC duals
pick fe0dc47 fill in infeasibility ray
pick 7797030 bug fix
pick b6855c1 bug fix
pick 8117e64 first test
pick 47e355c comment + another fact

# Rebase a274eb5..e13e77c onto a274eb5
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out

**Comment by emreyamangil** [comment]
OMG! That font size!!!! Sorryy!!!!

**Comment by joehuchette** [comment]
Yes, replace each ``pick`` on lines 2-6 with ``f``

**Comment by emreyamangil** [comment]
It says everything up to date :(

**Comment by joehuchette** [comment]
I rebased locally and pushed it to #634

**Comment by mlubin** [comment]
Closed by #634

**Pull request closed without merging**
