### PR TITLE
dot -> vecdot for multidimensional arrays

### PR DESCRIPTION
**Pull request by joehuchette**
@mlubin

### CODE REVIEW

**Comment by mlubin** [comment]
Leave in a deprecation warning for this use of ``dot``?

**Comment by mlubin** [comment]
Is vecdot part of Base in 0.3?

**Comment by joehuchette** [comment]
No, I thought for some reason that adding a method like this would work. Is it too tacky to define it ourselves with something like
```jl
eval(Base,:(vecdot(x,y) = ...))
```

**Comment by mlubin** [comment]
Just do ``import Base.vecdot`` on 0.4 and ``export vecdot`` on 0.3.

**Comment by mlubin** [comment]
What about the deprecation?

**Pull request merged**
