### PR TITLE
trailing whitespace is banished from JuMP...

### PR DESCRIPTION
**Pull request by joehuchette**
...at least until the next commit immediately following this one. This was bugging me, but it might not be worth screwing up git blame and creating merge conflicts.

### CODE REVIEW

**Comment by mlubin** [comment]
Why is there a merge conflict?

**Comment by joehuchette** [comment]
Not sure

**Comment by joehuchette** [comment]
So do we want this or no?

**Comment by mlubin** [comment]
No objection here

**Comment by IainNZ** [comment]
Fine with me!

**Pull request closed without merging**
