### PR TITLE
Support singleton anonymous variables

### LINKED ISSUE #844: parsing bug in @variable
In Julia 0.5 I run

```
m = JuMP.Model()
a = @variable(m, start=0)
```

I get the error
```
WARNING: imported binding for start overwritten in module Main
ERROR: MethodError: no method matching length(::Base.#start)
Closest candidates are:
  length(::SimpleVector) at essentials.jl:168
  length(::Base.MethodList) at reflection.jl:256
  length(::MethodTable) at reflection.jl:322
  ...
 in macro expansion; at /Users/coey/.julia/v0.5/JuMP/src/macros.jl:157 [inlined]
 in anonymous at ./<missing>:?
```

I get a similar error if I use the "basename" keyword.

### PR DESCRIPTION
**Pull request by joehuchette**
Closes #844 and #845

### CODE REVIEW

**Comment by joehuchette** [comment]
Note that this is still ambiguous:
```jl
@variable(m, Bin)
```

**Comment by joehuchette** [comment]
This is why I didn't allow it before actually, now that I remember

**Comment by mlubin** [comment]
Just throw an error in that case.

**Comment by chriscoey** [comment]
Thanks @joehuchette, this fixes an ugly minor issue I had in Pajarito

**Comment by joehuchette** [comment]
@mlubin objections to backporting this? I think this fixes an error on 0.14.1:
```
julia> @variable(m, lowerbound=1)
ERROR: UndefVarError: lowerbound not defined
 in macro expansion; at /Users/huchette/.julia/v0.5/JuMP/src/macros.jl:157 [inlined]
 in anonymous at ./<missing>:?
```

**Comment by mlubin** [comment]
If you'd like, but we're about to release anyway.

On Dec 12, 2016 3:46 PM, "Joey Huchette" <notifications@github.com> wrote:

@mlubin <https://github.com/mlubin> objections to backporting this? I think
this fixes an error on 0.14.1:

julia> @variable(m, lowerbound=1)
ERROR: UndefVarError: lowerbound not defined
 in macro expansion; at
/Users/huchette/.julia/v0.5/JuMP/src/macros.jl:157 [inlined]
 in anonymous at ./<missing>:?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/JuliaOpt/JuMP.jl/pull/847#issuecomment-266547684>, or mute
the thread

**Pull request merged**
