### PR TITLE
Add continuous relaxation of MINLP test problem

### PR DESCRIPTION
**Pull request by tkelman**
more demanding of AD than HS71, apparently (still debugging what OSIpoptSolver is doing wrong here, but worth adding the test case)

### CODE REVIEW

**Comment by mlubin** [comment]
Thanks for the test.
Have you gotten the derivative checker working with OSIpoptSolver?

**Comment by tkelman** [comment]
Had to redo the way I was dealing with solver options. To get options in an osol file to be applied, you need to specify not just option name and value, but also solver and type, and sometimes category if you want to change Ipopt or Cbc options when you're running Bonmin or Couenne on a MINLP.

So it looks like `nlp_solver = OsilSolver(solver="ipopt", OSOption("derivative_test", "second-order"), OSOption("print_user_options", "yes"), OSOption("print_level", 5))` (have not yet documented or tagged this version)

And yeah, there are some jacobian and hessian mismatches:
```
julia>     status = solve(m)

List of user-set options:

                                    Name   Value                used
            check_derivatives_for_naninf = yes                   yes
                         derivative_test = second-order          yes
                                max_iter = 20000                 yes
                             print_level = 5                     yes
                      print_user_options = yes                   yes

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.11.7, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Starting derivative checker for first derivatives.

* jac_g [    2,    0] =  1.0000000000000000e+00 v  ~ -9.9999999392252903e-01  [ 2.000e+00]
* jac_g [    2,    1] = -1.0000000000000000e+00 v  ~  1.0000000050247593e+00  [ 2.000e+00]
* jac_g [    0,    2] =  4.3675967223840445e-01 v  ~ -7.9999999957891532e-01  [ 1.237e+00]
* jac_g [    1,    2] =  5.4594959029800549e-01 v  ~ -9.9999999392252903e-01  [ 1.546e+00]
* jac_g [    1,    5] = -1.0000000000000000e+00 v  ~ -1.9999999878450581e+00  [ 5.000e-01]
* jac_g [    0,    6] = -8.0000000000000004e-01 v  ~  4.3675966796767474e-01  [ 1.237e+00]
* jac_g [    1,    6] = -2.0000000000000000e+00 v  ~  5.4594957485749662e-01  [ 2.546e+00]
Starting derivative checker for second derivatives.

*     0-th constr_hess[    6,    2] =  0.0000000000000000e+00    ~ -1.9870730119409863e-01  [ 1.987e-01]
*     0-th constr_hess[    6,    6] = -1.9870730343104007e-01 v  ~  0.0000000000000000e+00  [ 1.987e-01]
*     1-th constr_hess[    6,    2] =  0.0000000000000000e+00    ~ -2.4838412207295596e-01  [ 2.484e-01]
*     1-th constr_hess[    6,    6] = -2.4838412928880008e-01 v  ~  0.0000000000000000e+00  [ 2.484e-01]

Derivative checker detected 11 error(s).
```

**Comment by mlubin** [comment]
Those are pretty serious derivative mismatches...

**Comment by tkelman** [comment]
Columns 2 and 6 are switched in the hessian and on row 0 of the jacobian, row 2 of the jacobian is the wrong sign, and 2,5,6 on row 1 should be swapped with 6,2,5. Now how much C++ do I need to dig through to find the bug...

**Comment by IainNZ** [comment]
I have nothing to contribute but (a) wow thats messed up, and (b) good luck!

**Comment by tkelman** [comment]
Couenne solves it (as long as I give it a starting point where log can be evaluated, and loosen the acceptance tolerances), so the problem must be in the functions for evaluation-based solvers

**Comment by tkelman** [comment]
@andreaslundell reported the same issue, even using the same test problem, at https://projects.coin-or.org/OS/ticket/55. I just send a message to the OS mailing list to see if anyone has noticed the ticket yet (grumble grumble Trac grumble grumble).

**Comment by tkelman** [comment]
I think I at least found where the bug is, if not what's wrong about it. If I change the if statement to avoid this branch - https://github.com/coin-or/OS/blob/0fa09aaf337f76b1c84d9fed87ca572b1d7bd6a4/OS/src/OSCommonInterfaces/OSInstance.cpp#L5928-L5960 then things appear to work correctly. So either there are too many or too few levels of indirection happening, or some index set is assumed to be sorted when it isn't, or ... ?

**Comment by tkelman** [comment]
Finally - with that workaround in place for the Jacobian bug, and a patch to Ipopt to make it return infeasible instead of an unhandled exception when variable bounds are infeasible (this was making bonmin fail to solve the MIQP test problem), OsilSolver is finally clean on all of JuMP's tests.

**Comment by joehuchette** [comment]
Good to merge?

**Comment by mlubin** [comment]
LGTM

**Comment by tkelman** [comment]
Thanks to some pretty heroic detective work by Gus Gassmann, the jacobian-values-in-wrong-columns bug has a proper fix on upstream trunk now - https://github.com/tkelman/CoinOptServices.jl/blob/master/deps/os-jacobianbug.patch

Will still have to brush up on how to profile C++ code to figure out the major performance discrepancy on the Goddard example (and presumably other large nonlinear problems too).

**Pull request merged**
