### PR TITLE
document and test SCS

### PR DESCRIPTION
**Pull request by mlubin**

### CODE REVIEW

**Comment by mlubin** [comment]
@tkelman, there are some issues with downloading sourceforge binaries:

```
Processing archive: C:\Users\appveyor\.julia\v0.3\ECOS\deps\downloads\ecos-e05a605588c38ad72e843f36af17f8f84e4e2ccb.7z
 
Error: Can not open file as archive
```

```
Processing archive: C:\Users\appveyor\.julia\v0.3\GLPK\deps\downloads\winglpk-4.52.zip
 
Error: Can not open file as archive
```

```
Processing archive: C:\Users\appveyor\.julia\v0.3\SCS\deps\downloads\scs-1.0.7.7z
 
Error: Can not open file as archive
```
Do you know if this is transitory? It has also affected users: http://stackoverflow.com/questions/28440729/glpk-installation-error

**Comment by tkelman** [comment]
https://twitter.com/sfnet_ops

**Comment by tkelman** [comment]
We should probably make a point to checksum all our downloads. I think we have that capability in BinDeps but nobody uses it yet.

**Comment by mlubin** [comment]
@tkelman, ah yes. Though following the discussion at https://github.com/JuliaLang/BinDeps.jl/pull/87 it looks like it may not work on windows?

**Comment by tkelman** [comment]
It got ported to Julia in https://github.com/JuliaLang/BinDeps.jl/pull/88, it's just completely undocumented

**Pull request merged**
