### PR TITLE
add :(<=) symbols to constr_expr output for linear range constraints

### PR DESCRIPTION
**Pull request by tkelman**
looks like a simple fix to part of https://github.com/JuliaOpt/JuMP.jl/issues/350#issuecomment-70590225

### CODE REVIEW

**Comment by joehuchette** [comment]
Looks good to me. Any chance we can goad you into adding a test while you're in there? :)

**Comment by tkelman** [comment]
Shouldn't appveyor be running here? @mlubin looks like you don't have the webhook enabled for running on PR's. You might want to use some parts of https://github.com/timholy/Images.jl/pull/251/files

**Comment by tkelman** [comment]
I got greedy with something that I think should work, using the dummy NLP solver to solve a linear problem:
```
ERROR: LoadError: LoadError: MethodError: `loadproblem!` has no method matching loadproblem!(::DummyNLPModel, ::Base.SparseMatrix.SparseMatrixCSC{Float64,Int64}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Symbol)
Closest candidates are:
  loadproblem!(::SolverInterface.ConicModelWrapper, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any)
  loadproblem!(::GLPKMathProgInterface.GLPKInterfaceBase.GLPKMathProgModel, ::AbstractArray{T,2}, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any)
  loadproblem!(::ECOS.ECOSMathProgModel, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any)
 in solveLP at /home/travis/.julia/v0.4/JuMP/src/solvers.jl:223
 in solve at /home/travis/.julia/v0.4/JuMP/src/solvers.jl:36
 in test_nl_mpb at /home/travis/build/JuliaOpt/JuMP.jl/test/nonlinear.jl:218
 in include at ./boot.jl:248
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:248
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:312
 in _start at ./client.jl:396
while loading /home/travis/build/JuliaOpt/JuMP.jl/test/nonlinear.jl, in expression starting on line 228
while loading /home/travis/build/JuliaOpt/JuMP.jl/test/runtests.jl, in expression starting on line 33
```

Is it possible for an expression-tree solver to provide fallbacks that allow it to solve linear problems?

**Comment by mlubin** [comment]
> Is it possible for an expression-tree solver to provide fallbacks that allow it to solve linear problems?

It's definitely possible if someone writes the glue, but I think the simpler solution would be to force JuMP through the NLP pathway when the solver doesn't support ``loadproblem!``. We've discussed this a few times but never implemented it.

What do I need to do to set up the AppVeyor webhook for PRs?

**Comment by mlubin** [comment]
AppVeyor might work now.

**Comment by tkelman** [comment]
image
image

**Pull request merged**
