### PR TITLE
[release-0.9] Use --> for FactCheck

### PR DESCRIPTION
**Pull request by tkelman**
Would be good to get a tagged release of 0.9 that passes on recent 0.4. Anything against tagging 0.9.3 from this branch soonish?

### CODE REVIEW

**Comment by IainNZ** [comment]
This was stopping 0.9 passing on jl0.4?

**Comment by mlubin** [comment]
Nothing against tagging 0.9.3 except that we're hoping to tag 0.10 soonish

**Comment by joehuchette** [comment]
No reason not to tag

**Comment by tkelman** [comment]
No, technically this is just a deprecation warning fix, but the lack of b0dd5f2034dfaa27825f2156d2a062d21d8cb6e5 does cause 0.9.2 to fail on recent Julia 0.4.

**Comment by joehuchette** [comment]
I'll tag in a minute

**Pull request merged**
