### PR TITLE
Make doc version warning a floating box with magic, for #439

### PR DESCRIPTION
**Pull request by IainNZ**

### CODE REVIEW

**Comment by IainNZ** [comment]
@mlubin I haven't tested it on readthedocs exactly, but I used chrome to manually edit the page live in the browser and it looked fine. Just merge?

**Comment by mlubin** [comment]
Let's see

**Comment by mlubin** [comment]
Well it's definitely sufficiently annoying. CC @tkelman

**Comment by IainNZ** [comment]
Hah yes it is 👯

**Comment by mlubin** [comment]
The mobile experience isn't good, it blocks the navigation button

**Comment by joehuchette** [comment]
haha do you think we have many mobile visitors?

**Comment by mlubin** [comment]
5% of visitors, not really okay to not have the mobile page usable

**Pull request merged**
