### PR TITLE
Add SOC constr printing in model, more unicode

### PR DESCRIPTION
**Pull request by IainNZ**

### CODE REVIEW

**Comment by mlubin** [comment]
More unicode is always better

**Comment by IainNZ** [comment]
It'd be good to get this in to 0.10.1, or release - Martin noticed that SOC constraints weren't printing, I'd consider it a bug.

**Comment by mlubin** [comment]
Well 0.10.1 is already tagged and fixes JuMP being broken and unusable on julia master. Could be 0.10.2 though.

**Comment by IainNZ** [comment]
Good with me

**Comment by joehuchette** [comment]
:+1:

**Pull request merged**
