### PR TITLE
parsing bugfix, closes #551

### LINKED ISSUE #551: bug in addConstraint
On 0.4 only:
```
julia> m = Model();

julia> @defVar(m, x)
x

julia> f(z) = z
f (generic function with 1 method)

julia> @addConstraint(m, x ≤ f(5)^2)
ERROR: MethodError: `constructconstraint!` has no method matching constructconstraint!(::Float64, ::Symbol)
Closest candidates are:
  constructconstraint!(::JuMP.Variable, ::Symbol)
  constructconstraint!(::JuMP.GenericAffExpr{Float64,JuMP.Variable}, ::Symbol)
  constructconstraint!(::JuMP.GenericAffExpr{Float64,JuMP.Variable}, ::Any, ::Any)
```
This can also give the wrong answer sometimes:
```
julia> using JuMP

julia> m = Model();

julia> @defVar(m, x)
x

julia> f(z) = z
f (generic function with 1 method)

julia> @addConstraint(m, x ≤ f(x)^2)
x² ≤ 0
```

### PR DESCRIPTION
**Pull request by mlubin**
Looks like this code was never really tested? I think we need to verify code coverage before releasing 0.10, given the huge amount of new code.

### CODE REVIEW

**Comment by IainNZ** [comment]
Does codecov say its tested? I've been ignoring it for a while

**Comment by IainNZ** [comment]
Do we need the version check in Travis? I wonder if its smart enough to merge them

**Comment by mlubin** [comment]
Actually this code has been around since 0.7: https://github.com/JuliaOpt/JuMP.jl/commit/dcf17f595734fa847b2d0036c25611e5f323e74b

**Comment by mlubin** [comment]
And it's tested but just not on the path that caused the bug...

**Comment by IainNZ** [comment]
ah damn thats worst-case scenario

**Pull request merged**
