### PR TITLE
remove deprecated comparison operators for building constraints

### PR DESCRIPTION
**Pull request by mlubin**
Removing code is very satisfying

### CODE REVIEW

**Comment by IainNZ** [comment]
Are we losing any test coverage?

**Comment by mlubin** [comment]
Not all combinations of the new meaning of ``==`` are covered, but I figured we could do that later.

**Comment by IainNZ** [comment]
I'm more worried about the old meaning, the removed tests. We can still test those right, with a macro added?

**Comment by mlubin** [comment]
Those are already there

**Comment by mlubin** [comment]
Look right below all of the removed tests

**Comment by IainNZ** [comment]
Hah, of course, sorry

**Pull request merged**
