### PR TITLE
special case map for OneIndexedArrays

### PR DESCRIPTION
**Pull request by mlubin**
Ref https://github.com/JuliaOpt/JuMP.jl/commit/cc001eaac3865a06889aad9068c4b676c53eef66#commitcomment-12310195. Not sure what happened there.

This change doesn't fix any performance issues with getValue: https://github.com/JuliaOpt/JuMP.jl/commit/f3d3774f4ee20490ccf7453e71f008d923cc908d#commitcomment-11664585

### CODE REVIEW

**Comment by mlubin** [comment]
https://github.com/JuliaOpt/JuMP.jl/commit/450f9fed2058bf08ffe1fbe34ba668cf3b6ba319#commitcomment-12310299

**Comment by joehuchette** [comment]
Ipopt still doesn't install on OSX, and SCS failed another SDP test :(

**Comment by mlubin** [comment]
@staticfloat, any idea why Ipopt is failing to install with Homebrew on travis?
https://travis-ci.org/JuliaOpt/JuMP.jl/jobs/72213162#L214

**Comment by tkelman** [comment]
something to do with the fixup-libgfortran postinstall step not working maybe? https://github.com/staticfloat/homebrew-juliadeps/blob/master/libgfortran.rb

**Comment by staticfloat** [comment]
I'm betting that this is because GCC is bumped up to 5.X now, and that libgfortran formula is old.  I'll probably have to make a new one.

**Comment by tkelman** [comment]
What needs to happen there other than bumping the version number?

**Comment by staticfloat** [comment]
Looks like Homebrew main removed the `pkgconfig_files` helper function from their internal `Keg` class.  The long and the short is, copy-paste the old helper function into `libgfortran.rb`, rebuild the bottles for `5.2` and just keep on chugging.

**Comment by staticfloat** [comment]
Alright, `libgfortran` and `Ipopt` bottles are updated and pass `Pkg.test("Ipopt")`.  Hopefully things will work on Travis now.

**Comment by tkelman** [comment]
Did I/that manage to break the osx buildbots? I hit clean for openblas, arpack, etc, but now gfortran isn't being found right? http://buildbot.e.ip.saba.us:8010/builders/build_osx10.9-x64/builds/358/steps/shell_1/logs/stdio

Tried re-provisioning via rundeck but that doesn't seem to help.

**Comment by joehuchette** [comment]
Looks like things are working great again on Travis. Thanks a ton @staticfloat and @tkelman!

**Pull request merged**
