### PR TITLE
update xpress docs

### PR DESCRIPTION
**Pull request by joaquimg**
goes with #1103

### CODE REVIEW

**Comment by mlubin** [comment]
Change looks good but the version number is incorrect, should be 0.18 docs which we link to from the README.

**Comment by joaquimg** [comment]
Ok, only changing in 0.18 is ok?

**Comment by mlubin** [comment]
Yes, we don't update documentation for anything but the latest release (and the development version).

**Comment by joaquimg** [comment]
closed in favor of #1105

**Pull request closed without merging**
