### PR TITLE
Warn only once when getValue(x) doesn't work

### PR DESCRIPTION
**Pull request by joehuchette**
I was tired of getting pages of warnings that filled up the buffer on my terminal.

### CODE REVIEW

**Comment by mlubin** [comment]
This has been annoying for me too. You still might want to keep the variable name in there for concreteness.

**Comment by joehuchette** [comment]
I'm not sure if it'll work then; looks like ``warn_once`` [caches the string](https://github.com/JuliaLang/julia/blob/c18f18d14aacadac588e92a76226e5145448791b/base/util.jl#L361-L371).

**Comment by mlubin** [comment]
Oh. I'd add that the message will not repeat then, so that lack of a message doesn't imply that the problem was solved correctly

**Comment by joehuchette** [comment]
Think I like this implementation better.

**Comment by IainNZ** [comment]
Quite a nice little patch

**Comment by joehuchette** [comment]
Looks like SCS is broken on OS X nightlies:
```
while loading /Users/travis/build/JuliaOpt/JuMP.jl/test/model.jl, in expression starting on line 179
     - With solver SCS.SCSSolver
dyld: lazy symbol binding failed: Symbol not found: _validateLinSys
  Referenced from: /Users/travis/.julia/v0.4/Homebrew/deps/usr/lib/libscsdir64.dylib
  Expected in: flat namespace
dyld: Symbol not found: _validateLinSys
  Referenced from: /Users/travis/.julia/v0.4/Homebrew/deps/usr/lib/libscsdir64.dylib
  Expected in: flat namespace
/Users/travis/build.sh: line 41:  4213 Trace/BPT trap: 5       julia test/runtests.jl

```

**Pull request merged**
