### PR TITLE
Rename m -> model in test_expression

### PR DESCRIPTION
**Pull request by rohit-mp**
Is this fine? And do you have any suggestions or advice on how to go about adding tests to the changes made?

Closes https://github.com/JuliaOpt/JuMP.jl/issues/1992

### CODE REVIEW

**Comment by rohit-mp** [comment]
Fixes issue #1992

**Comment by blegat** [comment]
> And do you have any suggestions or advice on how to go about adding tests to the changes made?

No need to add test for this, it's just pure refactoring :)

**Comment by odow** [comment]
Thanks @rohit-mp

**Comment by rohit-mp** [comment]
Thanks guys!

**Pull request merged**
