### PR TITLE
Refactor printing & add precompile hints, 2-4x speedup

### PR DESCRIPTION
**Pull request by IainNZ**
# Test Script
```julia
# Compile speed tests
# Tests time to get from nothing to certain tasks
using JuMP  # Ensure compiled before running the tests

# Test 1
# Size 100, aff_str into model_str
tic()
run(`$(ENV["_"]) -e """
using JuMP
m = Model()
N = 100
@defVar(m, x[1:N])
@addConstraint(m, sum{i*x[i],i=1:N} >= N)
@time JuMP.aff_str(JuMP.REPLMode, m.linconstr[end].terms)
@time JuMP.model_str(JuMP.REPLMode, m)"""
`)
test1_time = toq()

# Test 2
# Size 100, model_str
tic()
run(`$(ENV["_"]) -e """
using JuMP
m = Model()
N = 100
@defVar(m, x[1:N])
@addConstraint(m, sum{i*x[i],i=1:N} >= N)
@time JuMP.model_str(JuMP.REPLMode, m)"""
`)
test2_time = toq()

# Test 3
# Size 10,000, print model
tic()
run(`$(ENV["_"]) -e """
using JuMP
m = Model()
N = 10000
@defVar(m, x[1:N])
@addConstraint(m, sum{i*x[i],i=1:N} >= N)
@time sprint(print, m)"""
`)
test3_time = toq()

# Test 4
# Size 10, 4 variables, print model
tic()
run(`$(ENV["_"]) -e """
using JuMP
m = Model()
N = 10
@defVar(m, x1[1:N])
@defVar(m, x2[1:N,f=1:N])
@defVar(m, x3[1:N,f=1:2:N])
@defVar(m, x4[[:a,:b,:c]])
@defVar(m, x5[[:a,:b,:c],[:d,"e",4]])
@addConstraint(m,
    sum{i*x1[i],i=1:N} +
    sum{i*f*x2[i,f],i=1:N,f=1:N} + 
    sum{i*f*x3[i,f],i=1:N,f=1:2:N} +
    sum(x4) >= N)
@time sprint(print, m)"""
`)
test4_time = toq()

println("Julia ", VERSION)
println("Current branch: $(chomp(readall(`git rev-parse --abbrev-ref HEAD`)))")
println("Current commit: $(chomp(readall(`git rev-parse HEAD`)))")
@printf("Test 1: %7.2f s\n", test1_time)
@printf("Test 2: %7.2f s\n", test2_time)
@printf("Test 3: %7.2f s\n", test3_time)
@printf("Test 4: %7.2f s\n", test4_time)
```

### CODE REVIEW

**Comment by IainNZ** [comment]
Test script 2
```julia
using JuMP
m = Model()
N = 100
@defVar(m, x[1:N])
@addConstraint(m, sum{i*x[i],i=1:N} >= N)


@time JuMP.model_str(JuMP.REPLMode, m)
@time JuMP.model_str(JuMP.REPLMode, m)
@time JuMP.model_str(JuMP.REPLMode, m)
@time JuMP.model_str(JuMP.REPLMode, m)
```
Master
```
3.307841 seconds (6.50 M allocations: 317.633 MB, 1.15% gc time)
0.000330 seconds (3.24 k allocations: 128.859 KB)
0.000269 seconds (3.24 k allocations: 128.859 KB)
0.000257 seconds (3.24 k allocations: 128.859 KB)
```
This PR
```
  2.830586 seconds (5.71 M allocations: 279.486 MB, 1.25% gc time)
  0.000321 seconds (3.25 k allocations: 129.156 KB)
  0.000247 seconds (3.25 k allocations: 129.156 KB)
  0.000247 seconds (3.25 k allocations: 129.156 KB)
```

**Comment by IainNZ** [comment]
I think there may be more speed to extract. I think the large number of arguments was causing problems. Its hard to figure out where the compilation slowness is coming from, but I realized how much a mess the arguments were when trying to precompile it - a mix of ASCII, UTF8... didn't seem healthy. Seems my guess was right, although my logic isn't necessarily right.

I think the other problem is that everything in this code seems to be `Union{ASCII,UTF8}` which I suspect is causing it to generate more code/do something suboptimal. You'll notice that the new dictionary approach forces everything to UTF8, although I still see unions everywhere.

**Comment by mlubin** [comment]
@joehuchette, does this conflict with your O̶n̶e̶I̶n̶d̶e̶x̶e̶d̶A̶r̶r̶a̶y̶ branch?

**Comment by IainNZ** [comment]
I think its about ready to merge. I tried looking for more speed improvements, but I'm not sure I can get them while we keep generating JuMPArrays on the fly.
I experiment with some refactoring of `cont_str` to improve type stability, by breaking it into functions. This helped fairly marginally, but should probably go in another PR just because it also makes it way easier to understand.

**Comment by IainNZ** [comment]
Oh, and of course, I can add the speed improvements from the other PR, once this is in.

**Comment by joehuchette** [comment]
It definitely conflicts, but that shouldn't hold up this being merged.

**Comment by IainNZ** [comment]
OK, might as well bite the bullet and get it in sooner rather than later

**Pull request merged**
