### PR TITLE
Update dot product of JuMP containers

### PR DESCRIPTION
**Pull request by cossio**
Fixing https://github.com/JuliaOpt/JuMP.jl/issues/940.
Updated version of previous pull: https://github.com/JuliaOpt/JuMP.jl/pull/941.

### CODE REVIEW

**Comment by joehuchette** [comment]
Looks good, thanks. Can you verify this fixes your spurious warning?

**Comment by cossio** [comment]
@joehuchette I don't know how to do it. I have never used my own julia branch. Currently I use stable 0.5. Can someone else test it?

**Comment by joehuchette** [comment]
Can confirm it fixes it. Will merge after Travis passes.

**Comment by cossio** [comment]
@joehuchette Great!

**Comment by mlubin** [comment]
Can we get some additional unit tests for the ``AbstractArray`` case? Does ``AbstractArray`` guarantee that we can index linearly?

**Comment by joehuchette** [comment]
I don't think this necessarily accesses anything linearly, the ``_dot`` method uses ``zip``.

**Comment by cossio** [comment]
@joehuchette Why is appveyor failing? Is this important?

**Comment by mlubin** [comment]
Appveyor is failing because Ipopt is broken on windows, safe to ignore for the moment.

**Comment by joehuchette** [comment]
@cossio it would be good to add the example from #940 as a test case. @mlubin what additional tests would you like to see?

**Comment by cossio** [comment]
@joehuchette  I don't know how to add tests. Can you show me?

**Comment by blegat** [comment]
@cossio You can check the files in the folder `JuMP/test` as examples.

**Comment by cossio** [comment]
Is there a way to test for warnings? (like `@test_throws` does for exceptions)

**Comment by joehuchette** [comment]
Not really, I would just add the test case and test that it returns the correct answer. If there is a regression in the future, we'll see the warning in the test log, and it will also be tremendously slow.

**Comment by cossio** [comment]
I added some tests. https://github.com/JuliaOpt/JuMP.jl/pull/947

**Pull request merged**
