### PR TITLE
[RFC] add setVarType

### PR DESCRIPTION
**Pull request by joehuchette**
ref #341. Will add docs + tests + NEWS if it looks alright.

### CODE REVIEW

**Comment by mlubin** [comment]
Type is a heavily overloaded word, what about ``setCategory``? No need to put ``Var`` in the name since the input is a Variable object.

**Comment by joehuchette** [comment]
Sounds good to me. Added everything else. Printing is still a bit broken:
```
julia> @defVar(m, x[1:3]);

julia> setCategory(x[2], :Int);

julia> print(m)
Min 0
Subject to
 x[i] free for all i in {1,2,3}
```

**Comment by IainNZ** [comment]
Printing thing is hella awkward...

Can this be made to work on `JuMPContainers` too? So you can set all the categories? I think this works on bounds already, or did at one point.

**Comment by joehuchette** [comment]
I think I got it figured out; pretty much you just "forget" that variables are in a JuMPContainer if they're not all the same category.

**Comment by joehuchette** [comment]
Win32 AppVeyor timed out, gonna merge anyway

**Pull request merged**
