### PR TITLE
Add Base.dot scalar fallback

### LINKED ISSUE #656: Problem with dot
```julia
using JuMP
function test()
    m = Model()
    @defVar(m, x[1:3])
    h = Float64[i for i in 1:3]
    @show h
    @show typeof(h)

    first = Array(JuMP.AffExpr, 3)
    first[1] = 10
    for i in 2:3
        first[i] = 10 + x[i]
    end
    @show first
    @show typeof(first)
    @show dot(h, first)

    second = Array(Any, 3)
    second[1] = 10
    for i in 2:3
        second[i] = 10 + x[i]
    end
    @show second
    @show typeof(second)
    @show dot(h, second)
end
test()
```

```
h = [1.0,2.0,3.0]
typeof(h) = Array{Float64,1}

first = [10,x[2] + 10,x[3] + 10]
typeof(first) = Array{JuMP.GenericAffExpr{Float64,JuMP.Variable},1}
dot(h,first) = 2 x[2] + 3 x[3] + 60

second = Any[10,x[2] + 10,x[3] + 10]
typeof(second) = Array{Any,1}
ERROR: LoadError: MethodError: `dot` has no method matching dot(::Float64, ::JuMP.GenericAffExpr{Float64,JuMP.Variable})
Closest candidates are:
  dot(::Number, ::Number)
 in vecdot at linalg/generic.jl:255
 [inlined code] from show.jl:127
 in test at ...
```

### PR DESCRIPTION
**Pull request by IainNZ**
Close #656

### CODE REVIEW

**Comment by IainNZ** [comment]
Seems like nightlies are screwed up

**Comment by mlubin** [comment]
Yep

**Comment by mlubin** [comment]
I can't reproduce any issues on julia master

**Comment by IainNZ** [comment]
YOLO

**Pull request merged**
