### PR TITLE
support for getobjbound etc from MathProgBase

### PR DESCRIPTION
**Pull request by mlubin**

### CODE REVIEW

**Comment by IainNZ** [comment]
Looks good!

**Comment by emreyamangil** [comment]
Live fix! Literally! :)

**Comment by IainNZ** [comment]
Forgot to come back to this? ;)

**Comment by mlubin** [comment]
Needs docs before we merge :)

**Comment by mlubin** [comment]
Updated with docs. It's not very well organized but maybe we'll leave that for that doc rewrite.

**Pull request merged**
