### PR TITLE
Add constructvariablecontainer! function

### PR DESCRIPTION
**Pull request by blegat**
Depends on #1038 
This could help creating different containers like `AxisArray`s #980

### CODE REVIEW

**Comment by chriscoey** [comment]
we are doing some housekeeping, so bumping this. anything we need to discuss?

**Comment by blegat** [comment]
@chriscoey Yes, I have just rebased it now that #1038 has been merged and I'd like to know what you think of it :)

**Comment by mlubin** [comment]
There's no documentation, what does this change?

**Comment by blegat** [comment]
Yes documentation should be added. It basically calls `constructvariablecontainer` with the extra arguments. This allows to do the special treatment of `SDP` and `Symmetric` not so special. The issue is that this not done in evaluation of the code so we still have `:SDP`  and `:Symmetric` as symbols. Therefore we should evaluate the part of extra that is used for building the container but not evalueate the part that is used to build each part yet... This still needs some thought but comments are welcome :)

**Comment by mlubin** [comment]
Looks like this is stale, can we close?

**Comment by blegat** [comment]
Yes, we can try to make the change later

**Pull request closed without merging**
