### PR TITLE
Unrecognized keyword arguments to solve should be handled

### PR DESCRIPTION
**Pull request by joehuchette**

### CODE REVIEW

**Comment by joehuchette** [comment]
```
julia> solve(m, this_should_throw=true)
ERROR: Unrecognized keyword arguments Any[(:this_should_throw,true)]
```

**Comment by joehuchette** [comment]
Open to suggestions

**Comment by mlubin** [comment]
Ah, I see the issue. I think this is okay, maybe improve the printing a bit

**Comment by joehuchette** [comment]
Open to suggestions on printing. Though it's breaking, this should maybe be backported, I got tripped up trying to pass ``relaxation=true`` on release-0.10.

**Comment by mlubin** [comment]
Just print out the names of the unrecognized keywords instead of ``Any[(:this_should_throw,true)]``?

**Pull request merged**
