### PR TITLE
add fallback methods for nonlinear functions on built-in types

### PR DESCRIPTION
**Pull request by joehuchette**
ref #349 

How does the error message look, @tkelman?

### CODE REVIEW

**Comment by tkelman** [comment]
Maybe replace "constraint" by "problem" in

> Are you trying to build a nonlinear constraint?

since this error could also occur in `@setObjective`, right?

**Comment by mlubin** [comment]
Looks good. Also we should give a similar message for division.

**Comment by mlubin** [comment]
And exponents?

**Comment by joehuchette** [comment]
AppVeyor 32bit timed out again...

**Comment by tkelman** [comment]
> AppVeyor 32bit timed out again...

There's some 0.4-only regression we need to figure out in how long it takes WinRPM to download the repodata xml files. It used to be 64-bit-only but then something changed to make it 32-bit-only. I think if you test AppVeyor on releases it shouldn't take as long, depending whether you want to check the combination of Windows and 0.4-only features regularly.

**Pull request merged**
