### PR TITLE
implement defVars macro

### PR DESCRIPTION
**Pull request by mlubin**
Missing docs. Let me know what you guys think about the ``->`` syntax. I think the end result is pretty nice.
@davidanthoff

### CODE REVIEW

**Comment by IainNZ** [comment]
So its only `->` for `@defVars`?

**Comment by joehuchette** [comment]
Yeah, I'm not sure I like using ``->``, but only in this one macro.

**Comment by mlubin** [comment]
``@defVars`` and [parameters to constraints](https://github.com/mlubin/JuMPChance.jl/blob/090efed3829f1aea90ec4c92dae3dd8d873a4b18/test/runtests.jl#L297). We don't have many choices for the syntax, ``=`` just doesn't parse like we would want it to.

**Comment by mlubin** [comment]
We can allow ``->`` in ``@defVar`` for consistency

**Comment by yeesian** [comment]
I'm confused why it is `->` instead of `<-` (if I understood it to be like R's assignment syntax)

**Comment by mlubin** [comment]
@yeesian, ``x <- y`` is parsed as ``x < -y``, so that wouldn't be an option. Agreed that it makes more sense though.

**Comment by IainNZ** [comment]
For me, the utility isn't outweighing the extra syntax/mental overhead...

**Comment by mlubin** [comment]
I guess we could try to manually override the precedence of ``=``

**Comment by joehuchette** [comment]
This also doesn't support the column-generation stuff (which would make working around the ``=`` parsing trickier).

**Comment by mlubin** [comment]
This does support column generation:
```
@defVars m begin
    0 <= z <= 5, objective->100.0, inconstraints->[maincon], coefficients->[1.0]
end
```

**Comment by joehuchette** [comment]
Ahh whoops, it just passes it along to ``@defVar`` I guess. It's worth taking a stab at working around the parsing, but things like this might get tricky:
```jl
julia> a = quote
       x[1:3], start = 3, coeffs=3
       end
quote  # none, line 2:
    (x[1:3],start) = (3,coeffs) = 3
end
```

**Comment by mlubin** [comment]
Well if it's possible to build a 1-1 mapping to undo the precedence of ``=``, it wouldn't be terrible to have the 20 lines of code to do so.
@JeffBezanson, here's an issue for us DSL builders

**Comment by davidanthoff** [comment]
Love the general utility of this. Would be great if ``=`` could be used instead of ``->``.

**Comment by mlubin** [comment]
What do we think about:
```
@defVars m begin
    0 ≤ x ≤ 1
    y ≥ 2; Int
    z ≤ 3; start = 10
    q; Bin; start = 0.5
end
```
We can keep the `=` for parameters if we use a semicolon as a separator. (Suggested by @StefanKarpinski)

**Comment by joehuchette** [comment]
Still not crazy about it, but it's the best proposal so far. I think it'd be better if we only use semicolons for "keyword arguments" like ``start``:
```jl
@defVars(m, begin
    0 ≤ x ≤ 1
    y ≥ 2, Int
    z ≤ 3; start = 10
    q, Bin; start = 0.5
```

**Comment by mlubin** [comment]
Having more than one type of separator is pretty confusing

**Comment by joehuchette** [comment]
Using commas in ``@addConstraint``, ``@defVar``, etc. and semicolons in ``@defVars`` is even more confusing. Mixing like this also matches with the distinction between regular/keyword arguments in julia syntax.

**Comment by mlubin** [comment]
We could switch to all semicolons in ``@addConstraint`` and ``@defVar``.

> Mixing like this also matches with the distinction between regular/keyword arguments in julia syntax.

You can go pretty far as a julia user without understanding this distinction, it only shows up when you're defining a function that takes in keyword arguments.

**Comment by joehuchette** [comment]
Another not totally satisfying solution that will work right now:
```jl
@defVars(m, begin
    0 ≤ x ≤ 1
    y ≥ 2, Int
    z ≤ 3, (start = 10)
    q, Bin, (start = 0.5, col)
end)
```

**Comment by mlubin** [comment]
The parentheses don't look too bad to me, but the use should be consistent for all modifiers, e.g.,
```
@defVars(m, begin
    0 ≤ x ≤ 1
    y ≥ 2, (Int)
    z ≤ 3, (start = 10)
    q, (Bin, start = 0.5, col)
end)
```

The parsed version of
```
y ≥ 2, (Int)
```
is the same as
```
y ≥ 2, Int
```
so there's no much we can do in that case.

However, there's a difference between
```
q, Bin, (start = 0.5, col)
```
and
```
q, (Bin, start = 0.5, col)
```
and I prefer the latter.

**Comment by mlubin** [comment]
Comments on the parentheses syntax?
@davidanthoff @yeesian @chriscoey

**Comment by yeesian** [comment]
I actually find the parentheses syntax quite pleasing (given the constraints in options available at the moment). I also prefer having the variable type in the parens

cc @JackDunnNZ

**Comment by yeesian** [comment]
One question: will the ordering of the arguments in the parentheses matter? (i.e. `vartype` comes before everything else, etc)

I guess the concern is whether there's a good way to distinguish between what goes into the parens and what doesn't. If we go by "non-parens for regular, parens for keyword args", it might lead to expectations that the arguments in the parens should be unordered.

**Comment by mlubin** [comment]
The ordering of the arguments inside the parentheses should not matter.

**Comment by davidanthoff** [comment]
I guess it is fine. Not ideal, but I also don't have a better idea :)

**Comment by mlubin** [comment]
Seems like a local optimum. I like it because it's easy to explain (put anything except the variable declaration in parentheses) and easy to parse.

**Comment by mlubin** [comment]
See https://github.com/JuliaOpt/JuMP.jl/pull/688 for the new implementation with parentheses as discussed

**Pull request closed without merging**
