### PR TITLE
support for duals in nonlinear problems

### PR DESCRIPTION
**Pull request by mlubin**
I punted a bit on quadratic constraints, would rather not deal with them yet.

### CODE REVIEW

**Comment by mlubin** [comment]
@joehuchette, SCS seems to be failing pretty consistently on linux nightly

**Comment by joehuchette** [comment]
Consistently failing in the same spot, or just consistently failing?

**Comment by mlubin** [comment]
This error seems pretty common:
```
[sdp] Robust uncertainty example
     - With solver SCS.SCSSolver
WARNING: [a,b] concatenation is deprecated; use [a;b] instead
 in depwarn at ./deprecated.jl:63
 in oldstyle_vcat_warning at ./abstractarray.jl:29
 in vect at abstractarray.jl:38
 in solveSDP at /home/travis/.julia/v0.4/JuMP/src/solvers.jl:632
 in solve at /home/travis/.julia/v0.4/JuMP/src/solvers.jl:27
 in anonymous at /home/travis/build/JuliaOpt/JuMP.jl/test/sdp.jl:416
 in context at /home/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:341
 in anonymous at /home/travis/build/JuliaOpt/JuMP.jl/test/sdp.jl:375
 in facts at /home/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:315
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in include at ./boot.jl:254
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:306
 in _start at ./client.jl:406
while loading /home/travis/build/JuliaOpt/JuMP.jl/test/sdp.jl, in expression starting on line 373
WARNING: Not solved to optimality, status: UnknownError
  Failure   :: (line:-1) :: With solver SCS.SCSSolver :: got UnknownError
    stat => :Optimal
  Failure   :: (line:-1) :: With solver SCS.SCSSolver :: got NaN
    abs(object - exact) => roughly(0,1.0e-5)
Out of 6 total facts:
  Verified: 4
  Failed:   2
ERROR: LoadError: FactCheck finished with 2 non-successful tests.
```

**Comment by joehuchette** [comment]
I've seen this one,  too. I'm not sure why SCS would be failing nondeterministically, but it's a little disconcerting.

**Pull request merged**
