### PR TITLE
Update AmplNLSolvers in tests to use exported solvers

### PR DESCRIPTION
**Pull request by JackDunnNZ**

### CODE REVIEW

**Comment by joehuchette** [comment]
LGTM. Is this alright @tkelman?

**Comment by tkelman** [comment]
Yeah. @JackDunnNZ should do `Pkg.tag("AmplNLWriter"); Pkg.publish()` though.

**Comment by JackDunnNZ** [comment]
Cool, I've created the pull request on metadata now

**Comment by joehuchette** [comment]
:+1:

**Pull request merged**
