### PR TITLE
Drop empty off-diagonal symmetry constraints for SDP constraints

### PR DESCRIPTION
**Pull request by joehuchette**
#765

### CODE REVIEW

**Comment by mlubin** [comment]
Cool, you mean #766?

**Comment by joehuchette** [comment]
Yep

**Comment by mlubin** [comment]
Ok, this seems easier than correcting ``issymmetric``. Is the new code covered by any tests?

**Comment by joehuchette** [comment]
No, I'm not sure how to test it

**Comment by mlubin** [comment]
You could directly look at the conicdata from the example in https://github.com/JuliaOpt/JuMP.jl/issues/766

**Comment by chriscoey** [comment]
@joehuchette, my hero

**Pull request merged**
