### PR TITLE
Jwscook/exampleswith optimizer

### PR DESCRIPTION
**Pull request by jwscook**
I found that the `Ipopt` model in `rosenbrock.jl` example required

```
model = Model(with_optimizer(Ipopt.Optimizer, max_cpu_time=60.0))
```
to make it work. I've gone ahead and made the changes to all the examples to construct a model via `with_optimizer`.

### CODE REVIEW

**Comment by mlubin** [comment]
What version of JuMP are you using? `with_optimizer` was deprecated, which is why it's not in the examples that match up with the latest release.

**Comment by jwscook** [comment]
```
(v1.3) pkg> st JuMP
    Status `~/.julia/environments/v1.3/Project.toml`
  [49dc2e85] Calculus v0.5.0 [`~/.julia/dev/Calculus`]
  [864edb3b] DataStructures v0.17.5 [`~/.julia/dev/DataStructures`]
  [f6369f11] ForwardDiff v0.10.6
  [4076af6c] JuMP v0.20.1
  [77ba4419] NaNMath v0.3.2+ [`~/.julia/dev/NaNMath`]
  [37e2e46d] LinearAlgebra 
```

**Comment by mlubin** [comment]
Please see the examples for the 0.20 release then: https://github.com/JuliaOpt/JuMP.jl/tree/release-0.20/examples. They have `with_optimizer`.

**Comment by odow** [comment]
Closing since the README in the `/examples` directory on Github also includes this warning:

image

**Pull request closed without merging**
