### PR TITLE
Add error messages for using NLExpr in quad/linear macros

### PR DESCRIPTION
**Pull request by IainNZ**
A user just hit this, I figured we can return a better error message.

### CODE REVIEW

**Comment by IainNZ** [comment]
Ambiguity warnings were not good, but I followed the warning messages and managed to address them.

**Comment by mlubin** [comment]
Seems like a good idea

**Comment by IainNZ** [comment]
Tangentially related, `@defNLExpr` prints out nasty innards when at the REPL, it'd almost be better just to have `(nonlinear expression)`, like Julia does with `(anonymous function)`

**Comment by IainNZ** [comment]
Looks like Appveyor had download issues, and Travis is backlogged on OSX, but otherwise, good to merge?

**Comment by joehuchette** [comment]
lgtm

**Pull request merged**
