### PR TITLE
update style recommendations for bangs

### PR DESCRIPTION
**Pull request by mlubin**
Some proposed updates based on the discussion in https://github.com/JuliaOpt/MathOptInterface.jl/issues/475. 

@IainNZ @matbesancon @juan-pablo-vielma @rdeits @IssamT

### CODE REVIEW

**Comment by matbesancon** [comment]
Nice addition to the explanation. This was not in the initial discussion, but I would add putting the mutated argument first, like `do_magic!(model, x, y)`. I found it a lot clearer in other packages to be able to identify it that way

**Comment by IainNZ** [comment]
lgtm

**Comment by mlubin** [comment]
> `!` is used to help readability, it is not an obligation and should not be used when redundant

To clarify, we should try to reduce scope for personal preferences when applying the rules the style guide. There's still a question of if a name clearly implies modification, but we should we should either omit `!` or use `!` based on the answer to that question.

**Comment by mlubin** [comment]
@matbesancon I agree the ordering point is important. I believe that's addressed by the link to the corresponding discussion in the Julia style guide.

**Pull request merged**
