### PR TITLE
Add precompilation hints for macros (~10% improvement)

### PR DESCRIPTION
**Pull request by IainNZ**
Supersedes #531 

```
Julia 0.4.0-dev+6805
Current branch: macroprecomp
Current commit: 4d7edc05f9d156f121db453880804f179b7088de
Test 1:    2.76 s
Test 2:    2.73 s
Test 3:    2.74 s
Test 4:    3.79 s

Julia 0.4.0-dev+6805
Current branch: macroprecomp
Current commit: 4d7edc05f9d156f121db453880804f179b7088de
Test 1:    2.76 s
Test 2:    2.75 s
Test 3:    2.69 s
Test 4:    3.91 s

-------------------------------------------------------

Current branch: macroprecomp
Current commit: aa6a9460d9a62e32c1c5b8d3798bf0d5b21d9f2e
Test 1:    2.76 s
Test 2:    2.64 s
Test 3:    2.74 s
Test 4:    3.92 s

Julia 0.4.0-dev+6805
Current branch: macroprecomp
Current commit: aa6a9460d9a62e32c1c5b8d3798bf0d5b21d9f2e
Test 1:    2.76 s
Test 2:    2.74 s
Test 3:    2.79 s
Test 4:    3.87 s

-------------------------------------------------------

Julia 0.4.0-dev+6805
Current branch: master
Current commit: 56b0f93d3081f5f2245a7edb54d6ea91bd7c58bb
Test 1:    3.08 s
Test 2:    3.00 s
Test 3:    3.11 s
Test 4:    4.22 s

Julia 0.4.0-dev+6805
Current branch: master
Current commit: 56b0f93d3081f5f2245a7edb54d6ea91bd7c58bb
Test 1:    3.14 s
Test 2:    3.02 s
Test 3:    3.20 s
Test 4:    4.15 s
```

### CODE REVIEW

**Comment by IainNZ** [comment]
This is just from the last PR so far, I'm adding more hints now based on tracing the types in the expanded test set, hope to get more.

**Comment by IainNZ** [comment]
I'm going to run all our tests and dump all methods, see if I can just algorithmically generate them.

**Comment by IainNZ** [comment]
Done, ready to merge once green

**Comment by joehuchette** [comment]
This won't work on v0.3

**Comment by IainNZ** [comment]
It isn't included on 0.3...

**Comment by joehuchette** [comment]
Ah, missed where the include was. Is it worth adding the script you used as a comment?

**Comment by IainNZ** [comment]
Unfortunately there is no script. I manually added code to print to a file, then just did sorted, uniq'd, and search replaced. Itd be neat to have something in Base to automatically report the argument types used.

**Comment by mlubin** [comment]
Precompile.jl needs an MPL header

**Pull request merged**
